PMM-6567 pg_stat_monitor.
Percona-Lab/pmm-api-tests pull request #124
Opened 2020-09-14 11:49 UTC by JiriCtvrtka

2020-09-16 09:10 UTC, BupycHuk requested changes
let's use disable_query_examples in tests

2020-09-18 08:56 UTC, JiriCtvrtka commented
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1104

PRs:
PMM - https://github.com/percona/pmm/pull/584
PMM managed - https://github.com/percona/pmm-managed/pull/457
PMM API tests - https://github.com/Percona-Lab/pmm-api-tests/pull/124
PMM agent - https://github.com/percona/pmm-agent/pull/186

2020-09-18 09:08 UTC, AlekSi commented
It should be `release/2.11`, not `release/2.11.0`

2020-09-18 09:12 UTC, BupycHuk approved these changes
@AlekSi it's my fault, I wrote wrong branch name to @JiriCtvrtka.
@JiriCtvrtka please create new branch and remove this one. Thank you.

2020-09-18 09:12 UTC, BupycHuk commented on inventory/agents_test.go
> +		// Test change API.
let's remove change part for this test, because we already have it in the test above.

2020-09-18 11:19 UTC, askomorokhov approved these changes

2020-09-24 11:26 UTC, merged