PMM-7015 Fix test.
Percona-Lab/pmm-api-tests pull request #169
Opened 2021-01-08 13:49 UTC by askomorokhov

https://jira.percona.com/browse/PMM-7015

Rel:
percona-platform/dbaas-controller#117
percona/pmm-managed#612

2021-01-08 13:50 UTC, BupycHuk requested changes

2021-01-08 13:50 UTC, BupycHuk commented on management/dbaas/psmdb_cluster_test.go
let's check that password is not empty

2021-01-08 13:52 UTC, askomorokhov commented on management/dbaas/psmdb_cluster_test.go
Added.

2021-01-10 01:34 UTC, BupycHuk approved these changes

2021-01-11 09:13 UTC, JiriCtvrtka approved these changes

2021-01-20 08:45 UTC, merged