PMM-6640 API for HAProxy.
Percona-Lab/pmm-api-tests pull request #183
Opened 2021-02-04 17:52 UTC by JiriCtvrtka

2021-02-04 22:52 UTC, BupycHuk requested changes
Let's update dependencies

2021-02-04 22:52 UTC, BupycHuk commented on management/haproxy_test.go
> +			Body: h_a_proxy.AddHAProxyBody{
please update dependencies

2021-02-05 06:37 UTC, JiriCtvrtka commented on management/haproxy_test.go
> +			Body: h_a_proxy.AddHAProxyBody{
Updated.

2021-02-05 11:20 UTC, BupycHuk approved these changes

2021-02-05 12:29 UTC, askomorokhov approved these changes

2021-02-09 13:36 UTC, merged