PMM-7338 API test for change check interval
Percona-Lab/pmm-api-tests pull request #211
Opened 2021-04-01 12:12 UTC by palash25

2021-04-04 13:59 UTC, BupycHuk requested changes
Please update tests.

2021-04-06 09:43 UTC, palash25 commented on server/checks_test.go
> +		for i, check := range resp.Payload.Checks {
will fix it

2021-04-08 11:01 UTC, artemgavrilov approved these changes

2021-04-08 12:04 UTC, BupycHuk approved these changes
A few comments, please fix them and merge

2021-04-08 12:04 UTC, BupycHuk commented on server/helpers.go
> +						Interval: &interval,
```suggestion
						Interval: pointer.ToString(security_checks.ParamsItems0IntervalSTANDARD),
```

2021-04-08 12:04 UTC, BupycHuk commented on server/checks_test.go
> +							Interval: &interval,
```suggestion
							Interval: pointer.ToString(security_checks.ParamsItems0IntervalSTANDARD),
```

2021-04-08 12:04 UTC, BupycHuk commented on server/checks_test.go
> +		var params *security_checks.ChangeSecurityChecksParams
let's remove these two variables from here and replace `params =` with `params :=` below

2021-04-08 12:04 UTC, BupycHuk commented on server/checks_test.go
> +		var params *security_checks.ChangeSecurityChecksParams
here and in other places where it's possible

2021-04-08 12:13 UTC, palash25 commented
done

2021-04-08 13:41 UTC, merged