PMM-7832 skip test for s3 config
Percona-Lab/pmm-api-tests pull request #215
Opened 2021-04-14 14:05 UTC by Dasio

[PMM-7832](https://jira.percona.com/browse/PMM-7832)

- [ ] Build: https://github.com/Percona-Lab/pmm-submodules/pull/0

- [ ] Links to other linked pull requests (optional).
- managed - https://github.com/percona/pmm-managed/pull/728
---
- [ ] Tests passed.
- [ ] Feature build pass.
- [ ] (Re)requested review.
- [ ] Fix conflicts with target branch.
- [ ] Update API dependency.
- [ ] Update jira ticket description if needed.
- [ ] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

2021-04-14 14:11 UTC, BupycHuk requested changes

2021-04-14 14:11 UTC, BupycHuk commented on management/backup/locations_test.go
> +			t.Skip()
let's add some info in skip

2021-04-14 14:33 UTC, oter approved these changes

2021-04-15 17:01 UTC, artemgavrilov approved these changes

2021-04-21 19:25 UTC, BupycHuk approved these changes

2021-04-21 19:43 UTC, merged