PMM-8155 Backup scheduling
Percona-Lab/pmm-api-tests pull request #221
Opened 2021-06-23 13:03 UTC by Dasio

https://jira.percona.com/browse/PMM-8155

PMM-managed: https://github.com/percona/pmm-managed/pull/778
API: https://github.com/percona/pmm/pull/748

2021-06-24 11:58 UTC, oter requested changes

2021-06-24 11:58 UTC, oter commented on management/backup/backups_test.go
> +	"github.com/AlekSi/pointer"
Let's keep imports order consistent.

2021-06-24 11:58 UTC, oter commented on management/backup/backups_test.go
> +	assert.NoError(t, err)
let's also check that scheduled backup was removed from the db.

2021-06-24 12:23 UTC, oter approved these changes

2021-06-27 12:03 UTC, BupycHuk approved these changes

2021-06-29 18:26 UTC, artemgavrilov approved these changes

2021-07-08 09:36 UTC, oter approved these changes

2021-07-13 13:57 UTC, merged